openapi: 3.0.0
info:
  version: 1.26.0-Rev.4
  title: Incremental Dashboard API
  description: >
    The Incremental Dashboard API is a modern REST API based on the OpenAPI
    specification. Date: 04 January, 2023. [Recent
    Updates](https://mini.io/whats-new/)
  contact:
    name: Meraki Developer Community
    url: https://meraki.io/community
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.mini.com/api/v1

security:
  - mini_api_key: []
   
      
paths:
  /organizations:
    get:
      description: List the organizations that the user has privileges on
      operationId: getOrganizations
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Organization ID
                    name:
                      type: string
                      description: Organization name
                    url:
                      type: string
                      description: Organization URL
                    api:
                      type: object
                      properties:
                        enabled:
                          type: string
                          description: Enable API access
                          enum:
                            - "true"
                            - "false"
                      description: API related settings
                    licensing:
                      type: object
                      properties:
                        model:
                          type: string
                          enum:
                            - co-term
                            - per-device
                            - subscription
                          description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                      description: Licensing related settings
                    cloud:
                      type: object
                      properties:
                        region:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of region
                          description: Region info
                      description: Data for this organization
              example:
                - id: '2930418'
                  name: My organization
                  url: https://dashboard.meraki.com/o/VjjsAd/manage/organization/overview
                  api:
                    enabled: "true"
                  licensing:
                    model: co-term
                  cloud:
                    region:
                      name: North America
        '401': 
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: error ID
              example:
                id: abc-uiuid-123
        '429': 
          description: too many requests
        '500':
          description: internal service error
        '502':
          description: bad gateway
        '503':
          description: service unavailable
        '504':
          description: gateway timeout
      summary: List the organizations that the user has privileges on
      tags:
        - read-only
        - read-server3
    post:
      description: Create a new organization
      operationId: createOrganization
      requestBody:
        description: organization to create
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the organization
              required:
                - name
            example:
              name: My organization
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Organization ID
                  name:
                    type: string
                    description: Organization name
                  url:
                    type: string
                    description: Organization URL
                  api:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: Enable API access
                    description: API related settings
                  licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing related settings
                  cloud:
                    type: object
                    properties:
                      region:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of region
                        description: Region info
                    description: Data for this organization
              example:
                id: '2930418'
                name: My organization
                url: https://dashboard.meraki.com/o/VjjsAd/manage/organization/overview
                api:
                  enabled: true
                licensing:
                  model: co-term
                cloud:
                  region:
                    name: North America
        '400': 
          description: bad request
        '401': 
          description: unauthorized
        '403': 
          description: forbidden
        '429': 
          description: too many requests
        '500':
          description: internal service error
        '502':
          description: bad gateway
        '503':
          description: service unavailable
        '504':
          description: gateway timeout
      summary: Create a new organization
      tags:
        - read-only
  /organizations/{organizationId}:
    get:
      description: Return an organization
      operationId: getOrganization
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          description: Organization Identifier
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Organization ID
                  name:
                    type: string
                    description: Organization name
                  url:
                    type: string
                    description: Organization URL
                  api:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: Enable API access
                    description: API related settings
                  licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing related settings
                  cloud:
                    type: object
                    properties:
                      region:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of region
                        description: Region info
                    description: Data for this organization
              example:
                id: '2930418'
                name: My organization
                url: https://dashboard.meraki.com/o/VjjsAd/manage/organization/overview
                api:
                  enabled: true
                licensing:
                  model: co-term
                cloud:
                  region:
                    name: North America
        '401': 
          description: unauthorized
        '403': 
          description: forbidden
        '429': 
          description: too many requests
        '500':
          description: internal service error
        '502':
          description: bad gateway
        '503':
          description: service unavailable
        '504':
          description: gateway timeout
      summary: Return an organization
      tags:
        - read-server
    put:
      description: Update an organization
      operationId: updateOrganization
      parameters:
        - name: organizationId
          in: path
          schema:
            type: string
          required: true
          description: Organization Identifier
      requestBody:
        description: organization to update
        content:
          application/json:
            schema:   
              type: object
              properties:
                name:
                  type: string
                  description: The name of the organization
                api:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      description: If true, enable the access to the Cisco Meraki Dashboard API
                  description: API-specific settings
            example:
              name: My organization
              api:
                enabled: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '400': 
          description: bad request
        '401': 
          description: unauthorized
        '403': 
          description: forbidden
        '429': 
          description: too many requests
        '500':
          description: internal service error
        '502':
          description: bad gateway
        '503':
          description: service unavailable
        '504':
          description: gateway timeout
      summary: Update an organization
      tags:
        - configure
    delete:
      description: Delete an organization
      operationId: deleteOrganization
      parameters:
        - name: organizationId
          in: path
          schema:
            type: string
          required: true
          description: Organization Identifier

      responses:
        '204':
          description: Successful operation
        '401': 
          description: unauthorized
        '403': 
          description: forbidden
        '429': 
          description: too many requests
        '500':
          description: internal service error
        '502':
          description: bad gateway
        '503':
          description: service unavailable
        '504':
          description: gateway timeout
      summary: Delete an organization
      tags:
        - configure  
components:
  securitySchemes:
    mini_api_key:
      type: apiKey
      name: X-Incremental-Dashboard-API-Key
      in: header
      description: Basic Auth Key
  schemas:
    Organization:
      type: object
      properties:
        id:
          type: string
          description: Organization ID
        name:
          type: string
          description: Organization name
        url:
          type: string
          description: Organization URL
        api:
          type: object
          properties:
            enabled:
              type: boolean
              description: Enable API access
          description: API related settings
        licensing:
          type: object
          properties:
            model:
              type: string
              enum:
                - co-term
                - per-device
                - subscription
              description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
          description: Licensing related settings
        cloud:
          type: object
          properties:
            region:
              type: object
              properties:
                name:
                  type: string
                  description: Name of region
              description: Region info
          description: Data for this organization
      example:
        id: '2930418'
        name: My organization
        url: https://dashboard.meraki.com/o/VjjsAd/manage/organization/overview
        api:
          enabled: true
        licensing:
          model: co-term
        cloud:
          region:
            name: North America



tags:
  - name: read
    description: "Read Operations"
  - name: configure
    description: "Read/Write Operations"